# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site.
# These values are expected to rarely change. If you are editing this file
# very often, consider using Jekyll's data files feature.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

## Site settings
## https://jekyllrb.com/docs/configuration/

title: QUnit
description: "The powerful, easy-to-use JavaScript testing framework."
# the base hostname and protocol for your site
url: "https://qunitjs.com"
# the subpath of your site, e.g. /blog
baseurl: ""

plugins:
  # https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Theme
# We have a custom theme so the Jekyll is ignored.
# But, the default theme setting for github-pages is 'primer',
# which Jekyll would still try to compile. This is a problem because
# since at least 2015, the combination of Jekyll/Sass/Primer is
# broken and simply doesn't compile out of-the-box.
#
# - https://github.com/jekyll/jekyll/issues/7426
# - https://github.com/jekyll/jekyll/issues/4268
# - https://github.com/sindresorhus/gulp-ruby-sass/issues/232
# - etc.
#
# Workaround by using the 'minima' for this no-op setting,
# which does compile an (unused) file without issue.
theme: minima
amethyst:
  twitter: qunitjs
  github: qunitjs
  gitter: qunitjs/qunit

# Conversion
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1,2"

# Search
algolia:
  application_id: HOJ487LP0L
  # Which index the Travis job will create/update
  # with the content of the current Jekyll site.
  # The auth key for this is injected as secure env variable.
  index_name: qunitjs
  files_to_exclude:
    # Index destination instead of intermediary
    - guides.md
  # Auth key for client-side search queries.
  search_only_api_key: aed00982db05bd21dd05310be057bda8

# Input files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - CNAME
  - vendor

# Output
permalink: title/
